### ISSUE TITLE
Information about visualization at github.io project page

### ISSUE THREAD

**Issue by alvinjinsung** [zhaihongjia/SplatLoc#1]
Hi! Thank you for an amazing work!

I just wanted to know if there is a visualization code like the one in the github.io project page (video of localization process)
If there is, can you provide where it is and if there isn't, information about how it is generated would be so helpful!

**Comment by zhaihongjia** [comment]
Hi, I used Open3D to draw the demo video. If you want to achieve a similar effect, you need to prepare a 3D Mesh, 2D RGB image, estimated pose, and 2D-3D matching pairs (2D image pixels and 3D points). I've been preparing CVPR recently, and I'll release this visualization code at the end of this month.

**Comment by alvinjinsung** [comment]
Thank you for your reply! Will the released code be updated on this repo or somewhere else?

**Comment by Tigro-Amur** [comment]
I need the visualization code too. So I'm curious about when and where will the visualization code be uploaded.

**Comment by zhaihongjia** [comment]
I upload the visualization codes at https://github.com/zhaihongjia/SplatLoc/tree/main/visualizations

**Comment by Tigro-Amur** [comment]
Thank you for uploading the visualization codes.
