### ISSUE TITLE
关于decoder.py代码的一个疑惑

### ISSUE THREAD

**Issue by wyb2333** [zhaihongjia/SplatLoc#2]
![image](https://github.com/user-attachments/assets/7dbdb888-7f87-4e4b-86ba-000c3a096117)
这里if-else下的内容是完全一样的，那这个if-else有什么意义吗？

**Comment by zhaihongjia** [comment]
你好，这个应该是我早期测试归一化linear weight和margin时候遗留下来的hard code，我在提交时没有处理干净。
