### ISSUE TITLE
AR application code

### ISSUE THREAD

**Issue by zheYan5** [zhaihongjia/SplatLoc#3]
Hi, thank you for your fantastic work!  Will you make your AR application code public? If so, when?

**Comment by zhaihongjia** [comment]
Hello, the AR demos were made by the collaborators of RayNeo. Currently, there is no plan to release the code. If it is released later, I will @ you.

**Comment by zheYan5** [comment]
Thanks.  Is the blanket in the AR demo modelled based on 3DGS? How did you do it? Took some pictures of a real blanket and then reconstructed it based on 3DGS?

**Comment by zhaihongjia** [comment]
This effect was achieved using blender app which is similar to the NeuralRecon demo. https://zju3dv.github.io/neuralrecon/

**Comment by zheYan5** [comment]
Thank you very much!
