### ISSUE TITLE
Collision handling

### ISSUE THREAD

**Issue by AnyinSong** [zhaihongjia/SplatLoc#4]
Thanks for sharing such an interesting work!
When handling the collisions between the virtual blanket and the reconstructed scene,  do you need to get the meshes of the scene? If so, how to do it?   Thank you.

**Comment by zhaihongjia** [comment]
Hello, this requires the scene mesh. You can use the TSDF Fusion algorithm to get the mesh based on the depth and RGB obtained by 3DGS-based rendering. Or, you can directly use the mesh provided in the dataset.

**Comment by AnyinSong** [comment]
Thanks for clarifying！
